name: Sample demo file.
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: list of file
        run: ls
      - name: read the file
        run: cat demo.txt
      - name: set up java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: mvn commands
        run : mvn clean test package
      - name: mvn version
        run : mvn -v
        
      
